version: '3.8'

services:
  mlops_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: lab04-mlops-api:latest
    container_name: lab04_mlops_container
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=INFO
      - PORT=8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s
